---
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/photosadmin/piwigo/config:/config
      - /home/photosadmin/piwigo/gallery:/gallery
    ports:
      - 80:80
    restart: unless-stopped

# ---
# services:
#   piwigo:
#     image: lscr.io/linuxserver/piwigo:latest
#     container_name: piwigo
#     environment:
#       - TZ='Australia/Sydney'
#       - PUID=1000
#       - PGID=1000
#     volumes:
#       - /home/photosadmin/piwigo/config:/config
#       - /home/photosadmin/piwigo/gallery:/gallery
# #     - /mnt/nobackup:/mnt/nobackup
# #     - /mnt/images:/mnt/images
# #     - /mnt/photos:/mnt/photos
#     ports:
#       - 80:80
#     restart: unless-stopped
