x-common-environment: &common_environment
  TZ: 'Australia/Sydney'
  PUID: 1000
  PGID: 1000

services:
  # ---------------------------------------------------------------------
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      <<: *common_environment
    volumes:
      - /home/photosadmin/piwigo/config:/config
      - /home/photosadmin/piwigo/gallery:/gallery
#     - /mnt/nobackup/immich_upload:/usr/src/app/upload
#     - /mnt/nobackup:/mnt/nobackup
#     - /mnt/images:/mnt/images
#     - /mnt/photos:/mnt/photos
    ports:
      - 80:80
    restart: unless-stopped
  # immich_server:
  #   container_name: immich_server
  #   image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
  #   depends_on:
  #     - immich_cache
  #     - immich_database
  #   command: [ "start.sh", "immich" ]
  #   ports:
  #     - 2283:3001
  #   volumes:
  #     - /mnt/nobackup/immich_upload:/usr/src/app/upload
  #     - /mnt/nobackup:/mnt/nobackup
  #     - /mnt/images:/mnt/images
  #   environment:
  #     <<: *common_environment
  #   restart: unless-stopped
  # # ---------------------------------------------------------------------
  # immich_microservices:
  #   container_name: immich_microservices
  #   image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
  #   depends_on:
  #     - immich_cache
  #     - immich_database
  #   command: [ "start.sh", "microservices" ]
  #   volumes:
  #     - /mnt/nobackup/immich_upload:/usr/src/app/upload
  #     - /mnt/images:/mnt/images
  #     - /mnt/nobackup:/mnt/nobackup
  #   environment:
  #     <<: *common_environment
  #   restart: unless-stopped
  #   extends:
  #     file: hardware_accelleration.yaml
  #     service: hwaccel
  # # ---------------------------------------------------------------------
  # immich_machine_learning:
  #   container_name: immich_machine_learning
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   volumes:
  #     - /home/photosadmin/model-cache:/cache
  #   ports:
  #     - 3003:3003
  #   environment:
  #     <<: *common_environment
  #   restart: unless-stopped
  # # ---------------------------------------------------------------------
  # immich_cache:
  #   container_name: immich_cache
  #   image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
  #   restart: unless-stopped
  # # ---------------------------------------------------------------------
  # immich_database:
  #   container_name: immich_database
  #   image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
  #   volumes:
  #     - /home/photosadmin/pgdata:/var/lib/postgresql/data
  #   environment:
  #     <<: *common_environment
  #   restart: unless-stopped
